---
- name: ensure dependencies are installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ gitlab_const[ansible_os_family]['dependencies'] }}"

- name: add gitlab repo for redhat
  block:
    - name: add gitlab repository
      ansible.builtin.yum_repository:
        name: gitlab
        description: gitlab YUM repo
        baseurl: "{{ gitlab_const[ansible_os_family]['gitlab_repo'] }}"
        gpgcheck: true
        gpgkey: "{{ gitlab_const[ansible_os_family]['gitlab_gpg'] }}"
        enabled: true
        module_hotfixes: true
  when: gitlab.repo == "gitlab"

- name: install gitlab packages. It takes some time
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{ gitlab_const[ansible_os_family]['packages'] }}"
  environment:
    LC_ALL: "en_US.UTF-8"
    LC_CTYPE: "en_US.UTF-8"