---
- name: "CA: create GitLab SSL configuration folder"
  file:
    path: "{{ gitlab_ca.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: "CA: Generate the private key"
  community.crypto.openssl_privatekey:
    path: "{{ gitlab_ca.path }}{{ gitlab_ca.common_name }}.key"
    passphrase: "{{ gitlab_ca.privatekey_passphrase | default(omit) }}"
    cipher: "{{ 'auto' if gitlab_ca.privatekey_passphrase is defined else omit }}"

- name: "CA: Generate CSR"
  community.crypto.openssl_csr:
    path: "{{ gitlab_ca.path }}{{ gitlab_ca.common_name }}.csr"
    privatekey_path: "{{ gitlab_ca.path }}{{ gitlab_ca.common_name }}.key"
    privatekey_passphrase: "{{ gitlab_ca.privatekey_passphrase | default(omit) }}"
    common_name: "{{ gitlab_ca.common_name }}"
    country_name: "{{ gitlab_ca.country_name | default(omit) }}"
    state_or_province_name: "{{ gitlab_ca.state_or_province_name | default(omit) }}"
    locality_name: "{{ gitlab_ca.locality_name | default(omit) }}"
    organization_name: "{{ gitlab_ca.organization_name | default(omit) }}"
    organizational_unit_name: "{{ gitlab_ca.organizational_unit_name | default(omit) }}"
    email_address: "{{ gitlab_ca.email_address | default(omit) }}"
    basic_constraints: "{{ gitlab_ca.basic_constraints | default(omit) }}"
    subject_alt_name: "{{ gitlab_ca.subject_alt_name }}"

- name: "CA: Self-sign"
  community.crypto.x509_certificate:
    path: "{{ gitlab_ca.path }}{{ gitlab_ca.common_name }}.crt"
    privatekey_path: "{{ gitlab_ca.path }}{{ gitlab_ca.common_name }}.key"
    privatekey_passphrase: "{{ gitlab_ca.privatekey_passphrase | default(omit) }}"
    csr_path: "{{ gitlab_ca.path }}{{ gitlab_ca.common_name }}.csr"
    provider: selfsigned
  notify: reconfigure gitlab