---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Unnessessary command
      ansible.builtin.shell:
        cmd: "{{ lookup('env', 'ANSIBLE_COMMAND') }}"
      when: lookup('env', 'ANSIBLE_COMMAND') | length > 0

  vars:
    # GitLab
    gitlab:
      enabled: true
      domain: "gitlab.local"
      repo: "gitlab"
      edition: "gitlab-ce"
    # GitLab -> install
    gitlab_install:
      enabled: true
    # GitLab -> self-signed Certificate Authority
    gitlab_ca:
      enabled: false
      path: "/etc/gitlab/ssl/"
      common_name: "{{ gitlab.domain }}"
      country_name: "US"
      state_or_province_name: "New York"
      locality_name: "New York City"
      organization_name: "Organization_Name"
      organizational_unit_name: "Community"
      email_address: "example@gmail.com"
      basic_constraints: 'CA:TRUE'
      subject_alt_name: "DNS:{{ gitlab.domain }}"
    # GitLab -> configure
    gitlab_config:
      enabled: false
      file: "gitlab.rb"
      src: "gitlab.rb.j2"
      backup: true
      data: |
        external_url 'http://{{ gitlab.domain }}/'
        registry_external_url 'http://{{ gitlab.domain }}'
        letsencrypt['enable'] = false

    # FirewallD
    firewalld:
      enabled: true
      service:
        enabled: true
        state: "started"
    # FirewallD -> rules
    firewalld_rules:
      service_http:
        enabled: true
        zone: "public"
        state: "enabled"
        service: "http"
        permanent: true
      service_https:
        enabled: true
        zone: "public"
        state: "enabled"
        service: "https"
        permanent: true

  tasks:
    - name: role darexsu gitlab
      include_role:
        name: darexsu.gitlab